# Generated by Django 3.1.5 on 2021-01-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biportal', '0003_auto_20210105_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
