# Generated by Django 3.1.5 on 2021-01-06 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biportal', '0005_auto_20210105_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bipage',
            options={'verbose_name': 'BI Page', 'verbose_name_plural': 'BI Pages'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Presentation', 'verbose_name_plural': 'Presentations'},
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='uploaded_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='file',
        ),
        migrations.AddField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snippet',
            name='embedded',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='snippet',
            name='h',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snippet',
            name='image_cropped',
            field=models.ImageField(null=True, upload_to='image_cropped/'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='image_rendered',
            field=models.ImageField(null=True, upload_to='image_rendered/'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='pages',
            field=models.ManyToManyField(to='biportal.Bipage'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='snippet',
            name='w',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snippet',
            name='x',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snippet',
            name='y',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MasterLayout',
        ),
    ]
