# Generated by Django 3.1.5 on 2021-01-07 15:51

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biportal', '0007_auto_20210107_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='image_cropped',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='image_cropped/', verbose_name='Report Snippet'),
        ),
    ]
