# Generated by Django 3.1.5 on 2021-01-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biportal', '0009_auto_20210107_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipage',
            name='ppt_page_layout',
            field=models.CharField(blank=True, choices=[('header', 'Header Page'), ('content1', 'Content With 1 Placeholder'), ('content2', 'Content With 2 Columns')], default='content1', max_length=20, null=True, verbose_name='PPT Page Layout'),
        ),
    ]
