# Generated by Django 3.1.5 on 2021-01-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biportal', '0011_presentation_ppt_master_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='embedded',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
