# Generated by Django 3.1.5 on 2021-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biportal', '0012_auto_20210109_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('htmltext', models.TextField(blank=True, null=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'HTML Text',
                'verbose_name_plural': 'HTML Texts',
            },
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='pages',
        ),
        migrations.AddField(
            model_name='bipage',
            name='snippets',
            field=models.ManyToManyField(to='biportal.Snippet'),
        ),
        migrations.AddField(
            model_name='bipage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='bipage',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='bipage',
            name='ppt_page_layout',
            field=models.CharField(blank=True, choices=[('header', 'Header Page'), ('content1', 'Content With 1 Placeholder'), ('content2', 'Content With 2 Columns')], default='content1', max_length=200, null=True, verbose_name='PPT Page Layout'),
        ),
        migrations.AddField(
            model_name='bipage',
            name='texts',
            field=models.ManyToManyField(to='biportal.SnippetHtml'),
        ),
    ]
