# Generated by Django 3.1.5 on 2021-01-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biportal', '0013_auto_20210112_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='bipage',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='exported_pages_pdf/'),
        ),
        migrations.AddField(
            model_name='bipage',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, upload_to='exported_pages_ppt/'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='exported_pres_pdf/'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, upload_to='exported_pres_ppt/'),
        ),
    ]
