# Generated by Django 3.1.5 on 2021-01-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biportal', '0014_auto_20210112_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bipage',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='exported_pages_pdf/', verbose_name='Exported PDF file'),
        ),
        migrations.AlterField(
            model_name='bipage',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, upload_to='exported_pages_ppt/', verbose_name='Exported PPT file'),
        ),
        migrations.AlterField(
            model_name='bipage',
            name='snippets',
            field=models.ManyToManyField(blank=True, null=True, to='biportal.Snippet'),
        ),
        migrations.AlterField(
            model_name='bipage',
            name='texts',
            field=models.ManyToManyField(blank=True, null=True, to='biportal.SnippetHtml'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='exported_pres_pdf/', verbose_name='Exported PDF file'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, upload_to='exported_pres_ppt/', verbose_name='Exported PPT file'),
        ),
    ]
