# Generated by Django 3.1.5 on 2021-01-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biportal', '0016_auto_20210113_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bipage',
            name='snippets',
            field=models.ManyToManyField(blank=True, to='biportal.Snippet'),
        ),
        migrations.AlterField(
            model_name='bipage',
            name='texts',
            field=models.ManyToManyField(blank=True, to='biportal.SnippetHtml'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
