---
# tasks file for retract-ec2


- include_vars:
    file: "{{ role_path }}/../../environments/{{ deployment_env }}/ec2_info.json"
    name: ec2_info

- debug:
    msg: "{{ ec2_info }}"

- debug:
    msg: "{{ ec2_info.instances | map(attribute='id') | list }}"

- name: remove ec2 stack
  cloudformation:
    stack_name: "{{ ec2_stack_name }}"
    state: "absent"
    region: "{{ aws_region }}"

################################################################################################################

- name: delete the vpc
  cloudformation:
    stack_name: "{{vpc_name}}"
    state: "absent"
  register: vpc_result
  ignore_errors: yes

################################################################################################################

- name: delete the key pair
  ec2_key:
    name: id_rsa
    state: absent

