---

AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create EC2 instance'
Resources:

##################################################################################################################

  ec2grrfIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /

  ec2grrfIamInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - Ref: ec2grrfIamRole

  ec2grrfIamRolePolicies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: ec2grrfIam
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 'ecr:*'
              - 'cloudtrail:LookupEvents'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'iam:CreateServiceLinkedRole'
            Resource: '*'
            Condition:
              StringEquals:
                'iam:AWSServiceName':
                  - replication.ecr.amazonaws.com
      Roles:
        - Ref: ec2grrfIamRole

##################################################################################################################

  ec2grrfSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ec2 grrf security group
      GroupName: grrf_ec2_group
      VpcId: vpc-0aed127187497dcc8
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: 8888
          ToPort: 8888
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 98.199.0.0/16

##################################################################################################################
# reference
# https://s3-us-west-1.amazonaws.com/cloudformation-templates-us-west-1/ELBSample.template
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: "id_rsa"
      SecurityGroupIds:
      - !Ref ec2grrfSecurityGroup
      InstanceType: t2.medium
      ImageId: ami-064d8dbbcc5ded164
      SubnetId: subnet-0929fee31f78c3936
      IamInstanceProfile:
        Ref: ec2grrfIamInstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 120
            DeleteOnTermination: 'true'
            Encrypted: 'true'
      Tags:
        -
          Key: Name
          Value: cts-aia-guardian-grrf-ec2

##################################################################################################################

  # ElasticLoadBalancer:
  #   Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
  #   Properties:
  #     AvailabilityZones:
  #       'Fn::GetAZs': ''
  #     Instances:
  #       - Ref: Ec2Instance
  #     Listeners:
  #       - LoadBalancerPort: '80'
  #         InstancePort: '80'
  #         Protocol: HTTP
  #     HealthCheck:
  #       Target:
  #         'Fn::Join':
  #           - ''
  #           - - 'HTTP:'
  #             - '80'
  #             - /
  #       HealthyThreshold: '3'
  #       UnhealthyThreshold: '5'
  #       Interval: '30'
  #       Timeout: '5'

  # reference:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html#cfn-ec2-elb-subnets
  ElasticLoadBalancer:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      # AvailabilityZones:
      # - 'us-east-1c'
      #   # 'Fn::GetAZs': ''
      Instances:
        - Ref: Ec2Instance
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
      Subnets:
        - 'subnet-0929fee31f78c3936'
      SecurityGroups:
        - Ref: ec2grrfSecurityGroup
      HealthCheck:
        Target:
          'Fn::Join':
            - ''
            - - 'HTTP:'
              - '80'
              - /
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'

Outputs:
  Ec2InstanceId:
    Description: 'EC2 instance.'
    Value: !Ref Ec2Instance
    Export:
      Name: !Sub '${AWS::StackName}-Ec2Instance'
  URL:
    Description: URL of the sample website
    Value:
      'Fn::Join':
        - ''
        - - 'http://'
          - 'Fn::GetAtt':
              - ElasticLoadBalancer
              - DNSName
