# Generated by Django 3.1.5 on 2021-01-08 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pptlayouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPTMasterLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlayout_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masterlayout_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Master PPT Layout',
                'verbose_name_plural': 'Master PPT Layouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PPTPageLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('web_page_layout', models.CharField(blank=True, choices=[('header', 'Header Page'), ('content1', 'Content With 1 Placeholder'), ('content2', 'Content With 2 Columns')], default='content1', max_length=20, null=True, verbose_name='Web Page Layout')),
                ('image_thumbnail', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='ppt_page_layouts/', verbose_name='Page Layout Thumbnail')),
                ('master_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagelayouts', to='pptlayouts.pptmasterlayout')),
            ],
            options={
                'verbose_name': 'PPT Page Layout',
                'verbose_name_plural': 'PPT Page Layouts',
            },
        ),
        migrations.DeleteModel(
            name='MasterLayout',
        ),
    ]
