# Generated by Django 3.1.5 on 2021-01-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptlayouts', '0002_auto_20210108_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pptmasterlayout',
            name='file',
        ),
        migrations.AddField(
            model_name='pptmasterlayout',
            name='master_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
