# Generated by Django 3.1.5 on 2021-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptlayouts', '0003_auto_20210108_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='pptmasterlayout',
            name='ppt_master_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
