# Generated by Django 3.1.5 on 2021-01-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pptlayouts', '0004_pptmasterlayout_ppt_master_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptmasterlayout',
            name='ppt_master_file',
            field=models.FileField(blank=True, null=True, upload_to='ppt_master_files/'),
        ),
    ]
